//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by RingingMaster.rc
//
#define ID_ADVANCED                     21
#define IDOK2                           22
#define IDTEST                          23
#define IDR_MAINFRAME                   101
#define IDR_TOUCHTYPE                   102
#define IDR_CRIBTYPE                    103
#define IDR_STRIKETYPE                  104
#define IDR_TOWERTYPE                   105
#define IDR_GRABTYPE                    106
#define IDR_MAPTYPE                     107
#define IDR_INTERNETTYPE                108
#define IDR_IMAGETYPE                   109
#define IDD_ABOUTBOX                    113
#define IDD_NOTATION_PLAIN              114
#define IDB_SPLASH                      115
#define IDD_STYLE_LINES                 116
#define IDD_STYLE_LAYOUT                117
#define IDC_REVERSE_POINTER             118
#define IDC_POINTER_COPY                119
#define IDR_METHOD_STYLE_DEFAULT        120
#define AAA_METHOD_DRAW_WND             121
#define IDR_MENU_PICTURES2              122
#define IDR_STANDARD                    123
#define IDS_STYLE_CAPTION               124
#define IDR_MENU_PICTURES1              125
#define IDR_METHOD_EDIT                 126
#define IDD_OPTIONS_METHOD              127
#define IDR_AVITEST                     128
#define IDD_GENERIC_EDIT                129
#define IDD_METHOD_EDIT                 130
#define IDR_WAIT_AVI                    130
#define IDR_TOOLBAR                     131
#define IDB_FOLDERS                     131
#define IDB_MUSIC_CTRL                  131
#define IDR_TOOLBAR_MAP                 131
#define IDR_FONT_POPUP                  132
#define IDR_FAVORITES_POPUP             133
#define IDR_HISTORY_POPUP               134
#define AAA_TIMER_DATA_OFF              136
#define AAA_TIMER_DATA_ON               137
#define IDD_SEARCH                      138
#define IDB_STATUS_READY                141
#define IDB_STATUS_ANIMATION            142
#define ID_TOWER_COMBO                  147
#define ID_FILTER_COMBO                 148
#define IDB_SUBITEMS                    150
#define IDD_OPTIONS_MISCELLANIOUS       153
#define IDD_STYLE_GENERAL               154
#define IDR_TOUCH                       155
#define IDR_TOUCH_MAIN                  155
#define ID_POPUP_CUSTOMIZE              177
#define IDR_FALSENESS_CNT_BAR           179
#define AAA_MUSIC_LIST                  180
#define ID_INDICATOR_ICON               180
#define AAA_FALSENESS_LIST              181
#define IDD_OPTIONS_TOUCH               182
#define IDB_LIGHTBULB                   184
#define IDD_TIP                         185
#define CG_IDS_TIPOFTHEDAY              186
#define CG_IDS_DIDYOUKNOW               188
#define AAA_GRAB_LIST                   189
#define ID_STYLE_MENU_00                210
#define ID_STYLE_MENU_01                211
#define ID_STYLE_MENU_02                212
#define ID_STYLE_MENU_03                213
#define ID_STYLE_MENU_04                214
#define ID_STYLE_MENU_05                215
#define ID_STYLE_MENU_06                216
#define ID_STYLE_MENU_07                217
#define ID_STYLE_MENU_08                218
#define ID_STYLE_MENU_09                219
#define ID_STYLE_MENU_MORE              220
#define ID_STYLE_MENU_SAVE_AS           221
#define IDD_STYLES_MORE                 222
#define AAA_PROPERTY_METHOD             223
#define IDB_PROPERTY_TAB                225
#define AAA_MUSIC_BAR                   227
#define AAA_PROPERTY_TABS               230
#define AAA_PROPERTY_BAR                231
#define IDS_NEW_TOUCH_CAPTION           233
#define AAA_PROPERTY_MUSIC              233
#define AAA_PROPERTY_VARIANCE           234
#define AAA_PROPERTY_SETUP              235
#define AAA_PROPERTY_STATUS             236
#define AAA_ANALYSIS_I_BAR              238
#define AAA_TIMER_LIST_SCROLL           239
#define AAA_PROPCMBBOX                  241
#define AAA_PROPEDITBOX                 242
#define AAA_PROPBTNCTRL                 243
#define AAA_EVENT_SIZE_GRIP             244
#define ID_VIEW_TOOLBARS                245
#define ID_TEXTCOLOR                    246
#define AAA_TIMER_NAG                   249
#define IDD_NAG                         250
#define AAA_TIMER_NAG_PROGRESS          251
#define IDD_REGISTER_PRODUCT            252
#define IDC_KEY                         253
#define IDD_NOTATION_CALLS              253
#define AAA_METHOD_WND                  253
#define AAA_TIMER_END_METHOD_WND        254
#define IDD_NOTATION_INFO               254
#define AAA_PREV_BUT                    255
#define IDD_NOTATION_CALL_POS_LEAD      255
#define IDD_METHOD                      256
#define AAA_MOUSE_LEFT_WND              257
#define IDD_NOTATION_NOTES              258
#define AAA_INFO_BUT                    258
#define IDD_CALL_POS_LEAD               259
#define AAA_PROPERTY_METHOD_LIST        259
#define IDD_CALL                        260
#define IDD_LEAD_HEAD                   261
#define IDD_STYLE_VIEW                  262
#define IDD_LEAD_LINES                  263
#define IDD_CALL_POS_METHOD             264
#define IDD_GENERIC_PROP                265
#define AAA_CRIB_BUT                    266
#define IDB_METHOD_EDIT                 310
#define AAA_ADD_NOTATION                310
#define IDB_PROP_BUT                    311
#define AAA_DELETE_NOTATION             311
#define IDB_NEW                         312
#define AAA_EXPLORE_NOTATION            312
#define IDB_EXPLORE                     313
#define IDB_DELETE                      314
#define IDB_NOTATION                    315
#define IDB_DOT_DOT_DOT                 316
#define IDB_INFO                        317
#define IDB_FIND                        318
#define IDB_PLUS                        319
#define IDB_MINUS                       320
#define IDB_UNDO                        321
#define IDB_STYLE                       322
#define IDD_PART_COUNT                  326
#define IDR_TOUCH_CONTEXT_GRID          328
#define IDR_TOUCH_CONTEXT_BLOCKS        329
#define IDD_NEW_METHOD_WIZ_1            330
#define IDC_POINTER_DRAG                330
#define IDD_NEW_METHOD_WIZ_2            331
#define IDD_NOTATION_EXPLORE            332
#define AAA_TOUCH_CARET_TIMER           332
#define IDC_RESIZENS                    332
#define IDD_LEAD_COUNT                  333
#define AAA_PROPERTY_VARIANCE_LIST      333
#define IDD_SERIAL_CONTROL_TEST         333
#define IDD_ROW_COUNT                   334
#define AAA_DELETE_VARIANCE             334
#define IDD_CIRCULAR_TOUCH_COUNT        335
#define AAA_ADD_VARIANCE                335
#define IDD_EDIT_BLOCK_LETTER           336
#define IDD_VARIANCE                    338
#define AAA_CRIB_SIZE_TIMER             339
#define IDD_TOWER                       341
#define IDR_PLAY                        344
#define AAA_UNDO_LIST                   345
#define IDB_FLAG                        345
#define IDD_OPTIONS_TOWER_SOUNDS        346
#define AAA_POPUP_LIST                  346
#define IDB_UP                          346
#define IDD_TOWER_DLG                   347
#define AAA_ADD_DEFINITION              347
#define IDB_DOWN                        347
#define AAA_DELETE_DEFINITION           348
#define IDD_DEFINITION                  348
#define IDR_TOOL                        348
#define AAA_POPUP_TOWER_COMBO           349
#define AAA_KILL_FOCUS_TIMER            350
#define AAA_ACTIVE_NOTATION             351
#define IDD_CALL_POS_AGREGATE           352
#define AAA_POPUP_SPIN                  352
#define IDD_CALL_POS_METHOD_SEL_DLG     353
#define AAA_POPUP_EDIT                  353
#define IDD_FALSENESS_DISPLAY_LIMIT     354
#define AAA_FIND_NOTATION               354
#define IDR_METHOD_STYLE_BLUE_LINE      354
#define IDD_START_AT_ROW                355
#define IDR_EXPLORER_TREE               355
#define AAA_PROPERTY_DEFINITION         355
#define IDD_ROW_CHOOSER                 356
#define IDB_ADD_DEFAULT                 356
#define IDR_EXPLORER_LIST_OFF           356
#define AAA_PROPERTY_DEFINITION_LIST    356
#define IDB_ADD_NUMBERED                357
#define IDR_EXPLORER_LIST               357
#define IDD_IMPORT_LOG                  357
#define AAA_PROPERTY_MUSIC_LIST         357
#define IDB_EXPLORER                    358
#define IDR_RESULTS_LIST                358
#define AAA_ADD_MUSIC                   358
#define IDD_MUSIC                       358
#define AAA_DELETE_MUSIC                359
#define IDR_EXPLORER_TREE_ROOT_USER     359
#define IDB_FILTER                      359
#define IDR_EXPLORER_LIST_RO            360
#define IDB_NO_FILTER                   360
#define AAA_ANALYSIS_TOUCH_TABS         360
#define AAA_ANALYSIS_LEAD_HEAD          361
#define IDB_PROOF_ANI                   361
#define IDR_TOUCH_CONTEXT_OFF           361
#define AAA_ANALYSIS_STATUS             362
#define IDB_PROOF_TICK                  362
#define ID_ST_1                         363
#define IDB_PROOF_CROSS                 363
#define IDD_GOTO_ROW                    363
#define ID_ST_2                         364
#define IDB_PROOF_CLEAR                 364
#define AAA_COURSE_HEAD                 364
#define ID_ST_3                         365
#define IDB_NEW_NEAR                    365
#define AAA_ANALYSIS_MULTI_BLOCK        365
#define ID_ST_4                         366
#define IDB_NEW_EXTREME                 366
#define ID_ST_5                         367
#define AAA_ANALYSIS_SPLICE             367
#define IDB_GOTO                        367
#define ID_ST_6                         368
#define AAA_ANALYSIS_ALL_WORK           368
#define IDB_BITMAP1                     368
#define IDB_FALSE_CTRL                  368
#define AAA_PLAY_POS_BAR                369
#define IDB_PRINT                       369
#define AAA_TRACK                       370
#define IDB_PREVIEW                     370
#define AAA_FALSENESS                   371
#define IDD_PRINT_ANALYSIS_SETUP        371
#define IDB_ROUNDS                      371
#define IDR_TOUCH_ANALYSIS              372
#define AAA_BLUE_LINE_VIEW              372
#define IDB_VIS_ROW                     372
#define AAA_TOUCH_VIEW                  373
#define IDB_NO_LIMIT                    373
#define IDC_TOUCHMAINPROPLIST           374
#define IDB_LEADHEADTABLE               374
#define IDD_CRIB                        374
#define AAA_PROP_EDIT_BUTTON            375
#define IDB_LEFT                        375
#define IDD_CALL_CAHNGES_EDITOR         375
#define AAA_PROP_ROOT_BUTTON            376
#define IDB_RIGHT                       376
#define IDD_OPTIONS_CALLED_CHANGES      376
#define IDB_SWAP                        377
#define IDB_OPTIONS                     378
#define IDR_TOWER_LIST                  378
#define AAA_LEAD_END                    379
#define IDB_PLAY                        379
#define ID_VIEW_TOOL_TOOLBAR            380
#define IDB_STOP                        380
#define IDD_RECORD_USER_FILTER          380
#define IDB_OPTIONS_CALLCHANGE          381
#define IDD_FILTER_DISTANCE             381
#define IDB_OPTIONS_TOWER_SOUNDS        382
#define IDD_CHOOSE_TOWER                382
#define IDB_TOWER_DETAILS               383
#define IDD_LIST_SELECT                 383
#define IDB_COPY                        384
#define IDD_GRAB_DETAILS                384
#define IDR_GRAB_LIST                   385
#define IDB_SEEK                        386
#define IDD_GRAB_ORDER                  386
#define IDR_TOOLBAR_TOUCH_MAIN          386
#define IDB_FIND1                       387
#define IDB_NOTES                       387
#define IDR_TOOLBAR_RECORD              387
#define IDR_TOOLBAR_DEFAULT             388
#define IDB_OPTIONS_USER                389
#define IDR_TOWER_LIST_OFF              389
#define IDB_HELP                        390
#define IDR_GRAB_LIST_OFF               390
#define IDB_LINK                        391
#define IDR_TOWER_ANALYSIS              391
#define AAA_POPUP_FILTER_COMBO          392
#define IDR_MAP                         392
#define IDR_TOOLBAR_INTERNET            393
#define IDR_TOOLBAR_CRIB                394
#define IDR_METHOD_CRIB                 395
#define IDR_TOOLBAR_IMAGE               397
#define IDR_IMAGE_VIEW                  398
#define IDR_METHOD_STYLE_CALLEDCHANGES  399
#define IDC_PROPERTYTREECRIB            400
#define IDR_TOOLBAR_TOUCH1              400
#define IDR_TOOLBAR_TOUCH_BLUE_LINE     400
#define IDC_PROPERTYTREEMAP             401
#define IDC_PROPERTYTREEINTERNET        402
#define IDD_EVENT_WAIT                  403
#define IDD_NOTATION_RESULTS            404
#define IDD_OPTIONS_LIBRARY             405
#define IDD_NEW_METHOD_WIZ_3            406
#define IDD_OPTIONS_MUSIC               407
#define IDD_CALL_TYPE_CHOOSER           408
#define IDD_SPLICE                      409
#define IDD_NOTATION_SPLICE_POS         410
#define IDD_GOTO_LEAD_ROW               411
#define IDD_STYLE_LINES_MINUS           412
#define IDD_OPTIONS_PRINT               413
#define IDD_LEAD_HEAD_HIGH              414
#define IDD_LEAD_HEAD_HIGHER            415
#define IDD_NOTES                       416
#define IDD_OPTIONS_MAP                 417
#define IDD_OPTIONS_TOWER               418
#define IDC_PROPERTYTREETOWER           419
#define IDD_OPTIONS_USER                419
#define IDD_SORT_DISTANCE               420
#define IDD_OPTIONS_GRABS               421
#define IDC_ANIMATE1                    423
#define IDD_OPTIONS_SCALES              423
#define IDC_PHELP                       424
#define IDC_TOUCHBLUELINEPROPLIST       425
#define IDR_RECORD                      428
#define IDB_FILTER_RECORDS              429
#define IDB_FILTER_EDIT                 430
#define IDB_USER                        431
#define AAA_ANALYSIS_TOWER_TABS         432
#define IDD_DIRECTION                   432
#define ID_GRAB_VIEW_CONTROL            432
#define AAA_ANALYSIS_TOWER_TOWER        433
#define IDD_LOGIC                       433
#define ID_TOWER_VIEW_CONTROL           433
#define IDD_FILTER_WEIGHT               434
#define AAA_TOWER_SOUNDS_FILES_ADVANCES_TIMER 434
#define IDD_FILTER_DIRECTION            435
#define IDR_RECORD_LOGIC                435
#define IDC_3D_WND                      435
#define IDD_SORT_DIRECTION              436
#define IDB_GRAB_CTRL                   436
#define ID_SIMULATOR_IP_SELECT_COMBO    436
#define IDD_TOWER_DB                    437
#define IDB_TRASH                       437
#define ID_ANALYSIS_ALL_THE_WORK        437
#define IDD_CHOOSE_GRAB                 438
#define IDR_INTERNET                    438
#define ID_ANALYSIS_STATUS              438
#define IDB_OPTIONS_MAP                 439
#define ID_ANALYSIS_COURSE_HEAD         439
#define IDB_CRIB                        440
#define ID_ANALYSIS_MUSIC               440
#define IDD_WEIGHT                      441
#define IDR_CRIB                        441
#define ID_ANALYSIS_LEAD_END            441
#define IDD_OPTIONS_INTERNET            442
#define IDR_IMAGE                       442
#define ID_ANALYSIS_CALLS_MADE          442
#define IDD_OPTIONS_CRIB                443
#define IDB_FLATTEN                     443
#define ID_ANALYSIS_MULTI_BLOCK         443
#define IDD_NEW_METHOD_WIZ_0            444
#define ID_ANALYSIS_SPLICE              444
#define IDB_FLATTEN_RED                 444
#define IDB_CUT                         445
#define ID_ANALYSIS_SPLICE_TRANSITION   445
#define IDD_SAVE_AS_SELECTION           446
#define IDB_PASTE                       446
#define ID_ANALYSIS_HOME_TOWER          446
#define IDB_TOWER_TREBLE                447
#define ID_RECORD_HOME_TOWER            447
#define IDB_CLONE                       448
#define ID_RECORD_SELECTED_TOWER        448
#define IDD_NOTATION_CALL_POS_AGREGATE  449
#define IDR_TOUCH1                      449
#define IDR_TOUCH_BLUE_LINE             449
#define ID_ANALYSIS_FALSENESS           449
#define IDD_NOTATION_CALL_POS_METHOD    450
#define ID_NEBUTTON                     450
#define IDD_NOTATION_LEAD_LINES         451
#define ID_NEEDIT                       451
#define IDD_NOTATION_COURSE_HEAD        452
#define IDC_CRIBPROPLIST                452
#define IDD_OPTIONS_MULTI_BELL_INTERFACE 453
#define IDC_MAPPROPLIST                 453
#define IDD_OPTIONS_MICROPHONE          454
#define ID_SIMULATOR_BTN                454
#define IDC_TOUCHSIMULATORPROPLIST      455
#define IDD_TOWER_SOUNDS_GENERAL        456
#define ID_SIMULATOR_MAINPANE           456
#define IDD_TOWER_SOUNDS_FILES          457
#define ID_SIMULATOR_SPLITTER           457
#define IDD_TOWER_SOUNDS_OPTIONS        458
#define ID_SIMULATOR_METHOD             458
#define IDD_TOWER_SOUNDS_SPEED          459
#define ID_SIMULATOR_ADD_BTN            459
#define IDD_TOWER_SOUNDS_TTS            460
#define ID_SIMULATOR_UPDATE_INPUT       460
#define IDD_TOWER_TTS                   461
#define IDD_OPTIONS_TTS                 462
#define ID_SIMULATOR_OPTION_BTN         462
#define IDB_SPEECH_BUBBLE               463
#define ID_SIMULATOR_STRIKING           463
#define IDB_VOLUME                      464
#define ID_SIMULATOR_INPUT_SPY          464
#define IDB_MIKE                        465
#define ID_ST_7                         465
#define IDB_SPEECH                      466
#define ID_ST_8                         466
#define IDR_GRAMMAR_MAIN                467
#define IDB_TRAIN                       467
#define ID_ST_9                         467
#define IDB_SOUND_SETTINGS              468
#define IDD_SPEECH_RECO_TEST            468
#define ID_ST_10                        468
#define IDB_SOUND_TEST                  469
#define IDD_OPTIONS_KEYBOARD            469
#define ID_STRIKING_CONTROLS            469
#define IDB_TICK                        470
#define IDD_KEYBOARD_TEST               470
#define ID_SIMULATOR_STRIKING_SINGLE_BELL1 470
#define IDB_BLANK                       471
#define IDD_TOWER_SOUNDS_FILES_ADVANCED 471
#define IDB_BELL                        472
#define IDD_BELL_3D                     472
#define ID_SIMULATOR_STRIKING_SINGLE_BELL2 472
#define IDB_KEYBOARD                    473
#define IDD_BELL_CIRCLE                 473
#define TOWER_SOUNDS_WINDOW_BASE        473
#define IDB_ADVANCED                    474
#define IDD_TOWER_ADVANCED              474
#define IDB_ADVANCED_BLUE               474
#define IDR_TASKPANE                    474
#define IDB_BELL_AND_TICK               475
#define IDD_OPTIONS_SIMULATOR_PROFILES  475
#define ID_NEW_TOWER_PROFILE            475
#define IDB_BELL_AND_DOTS               476
#define ID_STRIKE_GRAPH                 476
#define IDB_3D_EDIT                     477
#define IDD_SIMULATOR_PROFILE_GENERAL   477
#define ID_STRIKE_SET_BELL              477
#define IDB_BELL_CIRCLE                 478
#define IDD_TOWER_SOUNDS_BELL_INPUTS    478
#define ID_STRIKE_INFO                  478
#define IDB_ZOOM_IN                     479
#define ID_SIMULATOR_SET_BELL1          479
#define IDB_ZOOM_OUT                    480
#define ID_SIMULATOR_SET_BELL2          480
#define IDB_CENTER                      481
#define ID_STRIKEINFO                   481
#define IDB_ADVANCED_RED                482
#define ID_STRIKE_GRAPH_CTRL_BAR_GRAPH  482
#define IDB_COMBO_DOWN                  483
#define ID_SIMULATOR_INPUT_MAP          483
#define IDB_PORT                        484
#define IDC_TAB                         484
#define IDB_MBI                         485
#define IDC_MATRIX_FILTER_DESCRIP       485
#define IDR_PROP_TOUCH                  486
#define IDC_FILTER                      486
#define IDC_COLUMN                      487
#define IDR_FILE_NEW                    490
#define IDC_MATRIXPROPLIST              493
#define IDR_TOUCH_ANALYSIS_DROPDOWN     494
#define IDR_RECORD_ANALYSIS_DROPDOWN    495
#define IDR_PROP_DEFAULT                496
#define IDR_PROP_MATRIX                 497
#define IDR_POPUP_MDITABS               498
#define IDR_PROP_MAP                    498
#define IDR_TOOLBAR_TOUCH_SIMULATOR     499
#define IDR_TOUCH_SIMULATOR             499
#define IDR_TOUCH_MAIN1                 499
#define IDR_PLAY_SIMULATOR              500
#define IDB_TREE_ICONS                  501
#define IDB_FONT                        502
#define IDD_KEYBOARD_CAPTURE            503
#define IDD_MBI_SELECT                  504
#define IDB_SERIAL                      504
#define IDD_KEYBOARD_CAPTURE1           505
#define IDD_MBI_CAPTURE                 505
#define IDR_                            505
#define IDR_SIMULATOR                   505
#define IDB_MBI1                        505
#define IDB_SIMULATOR_ICONS             505
#define IDD_KEYBOARD_TEST1              506
#define IDD_MBI_TEST                    506
#define IDB_BLANK1                      506
#define IDB_IMAGE                       506
#define IDD_OPTIONS_SERIAL_COMMAND      507
#define IDB_PICTURE                     507
#define IDD_SERIAL_PORT_CONTROL_SELECT  508
#define IDB_MBI_CROSS                   508
#define IDD_SERIAL_CONTROL_CAPTURE      509
#define IDB_KEYBOARD_CROSS              509
#define IDD_KEYBOARD_SELECT             510
#define IDB_MIKE_CROSS                  510
#define IDD_SIMULATOR_PROFILE_GENERAL1  511
#define IDB_SERIAL_CROSS                511
#define IDD_PREVIEW_SIMULATOR_IMAGES    511
#define IDD_MBI_SELECT1                 512
#define IDD_SPEECH_SELECT               512
#define IDB_TOPLEFT                     512
#define IDD_TOWER_SOUNDS_SIMULATOR_DISPLAY 513
#define IDB_TOPRIGHT                    513
#define IDB_BOTTOMRIGHT                 514
#define IDD_STRIKE_CONTROLS             514
#define IDD_TOWER_SOUNDS_STRIKE_CONTROLS 514
#define IDB_BOTTOMRIGHT1                515
#define IDB_BOTTOMLEFT                  515
#define IDB_RESET                       516
#define IDB_RESET1                      517
#define IDB_RESETALL                    517
#define IDD_GENERIC_NUMBER_SPIN         519
#define IDR_METHOD_STYLE_SIMULATOR      519
#define IDR_SIMULATOR_STRIKING_SINGLE   520
#define IDR_TOOLBAR_DEFAULT1            520
#define IDR_TOOLBAR_STRIKE              520
#define IDD_TOWER_SOUNDS_BELL_INPUTS1   521
#define IDD_TOWER_SOUNDS_COMMAND_INPUTS 522
#define IDB_BITMAP2                     523
#define IDB_TASKS                       523
#define IDI_ICON1                       524
#define IDR_STRIKE                      525
#define IDR_STRIKE_GENERAL              526
#define IDR_SIMULATOR_GENERAL           527
#define ID_ST_11                        528
#define IDD_STRIKING_TEST               529
#define IDD_TOWER_WIZARD                532
#define IDD_TOWER_SOUNDS_CALL_INPUTS    533
#define IDD_TOWER_SOUNDS_METHOD_INPUTS  534
#define IDD_COLUMN_WIDTH                535
#define IDD_MATRIX_FILTER               536
#define IDD_TEXT_SELECT                 537
#define IDR_MENU1                       538
#define IDR_MATRIX_LOGIC                538
#define IDD_OPTION_SELECT               539
#define IDB_MATRIX_GRID                 540
#define IDD_FLOAT_SELECT                541
#define IDD_DOUBLE_SELECT               541
#define IDD_DIALOG1                     542
#define IDD_DATE_TIME_SELECT            542
#define IDD_DIALOG2                     543
#define IDD_INT_SELECT                  543
#define IDB_RIBBON_MAIN                 544
#define IDB_BITMAP3                     545
#define IDB_RIBBON_ICONS                545
#define IDB_BITMAP4                     546
#define IDB_RIBBON_FILELARGE            546
#define IDB_BITMAP5                     547
#define IDB_RIBBON_FILESMALL            547
#define IDB_BITMAP6                     548
#define IDB_RIBBON_HOMELARGE            548
#define IDB_BITMAP7                     549
#define IDB_RIBBON_HOMESMALL            549
#define IDR_MENU2                       550
#define IDR_WINDOWS_MENU                550
#define IDC_LINES_COLOR_0               1008
#define IDC_LINES_COLOR_1               1009
#define IDC_LINES_COLOR_2               1010
#define IDC_LINES_COLOR_3               1011
#define IDC_LINES_COLOR_4               1012
#define IDC_LINES_COLOR_5               1013
#define IDC_LINES_COLOR_6               1014
#define IDC_LINES_COLOR_7               1015
#define IDC_LINES_NUM_0                 1016
#define IDC_LINES_NUM_1                 1017
#define IDC_LINES_NUM_2                 1018
#define IDC_LINES_NUM_3                 1019
#define IDC_LINES_NUM_4                 1020
#define IDC_LINES_NUM_5                 1021
#define IDC_LINES_NUM_6                 1022
#define IDC_LINES_NUM_7                 1023
#define IDC_TEXT_COLOR_0                1024
#define IDC_TEXT_COLOR_1                1025
#define IDC_TEXT_COLOR_2                1026
#define IDC_TEXT_COLOR_3                1027
#define IDC_TEXT_COLOR_4                1028
#define IDC_TEXT_COLOR_5                1029
#define IDC_TEXT_COLOR_6                1030
#define IDC_TEXT_COLOR_7                1031
#define IDC_LINE_WIDTH_0                1032
#define IDC_LINE_WIDTH_1                1033
#define IDC_LINE_WIDTH_2                1034
#define IDC_LINE_WIDTH_3                1035
#define IDC_LINE_WIDTH_4                1036
#define IDC_LINE_WIDTH_5                1037
#define IDC_LINE_WIDTH_6                1038
#define IDC_LINE_WIDTH_7                1039
#define IDC_NAME                        1048
#define IDC_METHOD_DRAW_WND_HOLD        1064
#define IDC_METHOD_DRAW_ADD             1065
#define IDC_METHOD_DRAW_REMOVE          1066
#define IDC_METHOD_DRAW_CLEAR_ALL       1068
#define IDC_METHOD_DRAW_STYLE           1071
#define IDC_NOTATION                    1072
#define IDC_METHOD_DRAW_UNDO            1073
#define IDC_ALL_CHANGE                  1074
#define IDC_SEPERATOR                   1075
#define IDC_LINES_STATIC_TEXT           1076
#define IDC_LINES_STATIC_LINE_LEFT      1077
#define IDC_LINES_STATIC_LINE_CENTER    1078
#define IDC_STATIC_LINE_TITLE           1078
#define IDC_OPTIONS_MICL_AUTO_OPEN      1079
#define IDC_STATIC_LINE_NOTATION        1079
#define IDC_LINES_STATIC_LINE_RIGHT     1080
#define IDC_STATIC_LINE_STARTS          1080
#define IDC_LINES_STATIC_LINE_TOP2      1081
#define IDC_STATIC_LINE_FALSE_ROWS      1081
#define IDC_LINES_STATIC_LINE_TOP1      1082
#define IDC_STATIC_LINE_STYLE_NAME      1082
#define IDC_STATIC_LINE_CALLS           1082
#define IDC_LEFT                        1083
#define IDC_STATIC_LINE_FONT            1083
#define IDC_STATIC_LINE_STROKES         1083
#define IDC_LEFT_SPIN                   1084
#define IDC_STATIC_LINE_MUSIC_ROWS      1084
#define IDC_TOP                         1085
#define IDC_TOP_SPIN                    1086
#define IDC_WIDTH                       1087
#define IDC_WIDTH_SPIN                  1088
#define IDC_HEIGHT                      1089
#define IDC_HEIGHT_SPIN                 1090
#define IDC_LEADS                       1091
#define IDC_LEADS_SPIN                  1092
#define IDC_LEADS_CHECK                 1093
#define IDC_STATIC_LEADS                1094
#define IDC_SHOW_STARTS                 1098
#define IDC_SHOW_TITLE                  1099
#define IDC_SHOW_START_BLOBS            1100
#define IDC_EDIT_LINE_FONT              1102
#define IDC_SHOW_NOTATION               1102
#define IDC_TITLE_FONT                  1103
#define IDC_NOTATION_FONT               1104
#define IDC_SHOW_METHOD_TEXT            1105
#define IDC_SHOW_CALLS                  1105
#define IDC_SHOW_HANDSTROKE             1106
#define IDC_SHOW_BACKSTROKE             1107
#define IDC_LEAD_EDIT                   1109
#define IDC_LEAD_SPIN                   1110
#define IDC_BELL_EDIT                   1111
#define IDC_LEAD_COLOR                  1112
#define IDC_BELL_SPIN                   1113
#define IDC_BELL_COLOR                  1114
#define IDC_FALSE_ROW_COLOR             1115
#define IDC_MUSIC_ROW_COLOR             1116
#define IDC_STATIC_WIDTH                1117
#define IDC_START_FONT                  1118
#define IDC_STATIC_HEIGHT               1119
#define IDC_CALLS_FONT                  1119
#define IDC_STROKE_FONT                 1120
#define IDC_LIST1                       1123
#define IDC_BULB                        1124
#define IDC_SORTING                     1124
#define IDC_LIST_LEFT                   1124
#define IDC_STARTUP                     1125
#define IDC_DESCRIPTION                 1125
#define IDC_DESCRIPTION_DUMMY           1126
#define IDC_NEXTTIP                     1126
#define IDC_TIPSTRING                   1127
#define IDC_CREDITS                     1128
#define IDC_STYLE_NAME                  1133
#define IDC_ROW_NO_TYPE                 1136
#define IDC_ROW_NO_TYPE2                1137
#define IDC_STATIC_MEM                  1139
#define IDC_STATIC_DISK                 1140
#define IDC_MAIL                        1141
#define IDC_URL                         1142
#define IDC_REGISTER                    1146
#define IDC_PROGRESS                    1149
#define IDC_USE_DEFAULT_CALLS           1153
#define IDC_LEAD_HEAD                   1154
#define IDC_CALLS                       1156
#define IDC_CALL_POS_LEAD               1157
#define IDC_NOTATION_INFO               1158
#define IDC_CALL_POS                    1158
#define IDC_ADD_CALL                    1159
#define IDC_VIEW_LEADHEADS              1160
#define IDC_SET_STD_CALL                1161
#define IDC_CALL_POS_CHECK              1161
#define IDC_ADD_EXTREAM_PLACE_CALL      1162
#define IDC_ADD_NEAR_PLACE_CALL         1163
#define IDC_METHOD_WND_HOLD             1165
#define IDC_CALL_POS_ADD                1165
#define IDC_PLACE_STATIC                1166
#define IDC_CALL_POS_REMOVE             1166
#define IDC_ROW_STATIC                  1167
#define IDC_CALL_POS_ADD_DEFAULT        1167
#define IDC_LEAD_STATIC                 1168
#define IDC_CALL_POS_ENUM               1168
#define IDC_BELL_STATIC                 1169
#define IDC_MES                         1170
#define IDC_USE_DEFAULT_LEAD_LINES      1171
#define IDC_LEAD_LINES                  1172
#define IDC_NOTES                       1173
#define IDC_USE_DEFAULT_COURSE_HEAD     1173
#define IDC_CALL_NAME_SHORTHAND         1174
#define IDC_CALL_NOTATION               1175
#define IDC_CALL_NAME_LONGHAND          1176
#define IDC_CALL_NOTATION_STATIC        1177
#define IDC_CALL_EDIT                   1178
#define IDC_CALL_POS_EDIT               1179
#define IDC_REMOVE_AGREGATE             1180
#define IDC_STATIC_LINE_LAYOUT          1181
#define IDC_MOVE_UP                     1181
#define IDC_STATIC_LAYOUT               1182
#define IDC_MOVE_DOWN                   1182
#define IDC_STATIC_FONT                 1183
#define IDC_STATIC_LAYOUT2              1183
#define IDC_STATIC_STYLE_NAME           1184
#define IDC_STATIC_LINE_LAYOUT2         1184
#define IDC_STATIC_FALSE_ROWS           1185
#define IDC_STATIC_STARTS               1186
#define IDC_STATIC_TITLE                1187
#define IDC_STATIC_CALLS                1188
#define IDC_STATIC_STROKES              1189
#define IDC_ADD_LEAD_LINE               1190
#define IDC_STATIC_MUSIC_ROWS           1190
#define IDC_REMOVE_LEAD_LINE            1191
#define IDC_LEAD_LINE                   1192
#define IDC_ADD_DEFAULT_LEAD_LINE       1192
#define IDC_LEAD_LINE_EDIT              1193
#define IDC_COURSE_HEAD_EDIT            1193
#define IDC_POS                         1197
#define IDC_LEAD                        1201
#define IDC_LIST                        1203
#define IDC_CALL_POS_COLOR              1207
#define IDC_CALL_COLOR                  1208
#define IDC_NO_MAX_PART                 1208
#define IDC_NOTES_FONT_COLOR            1208
#define IDC_CHANGED_CH_COLOR            1209
#define IDC_PART_COUNT                  1209
#define IDC_METHOD_SPLICE_COLOR         1210
#define IDC_PART_COUNT_SPIN             1210
#define IDC_UNCHANGED_CH_COLOR          1211
#define IDC_LEAD_COUNT                  1211
#define IDC_LEAD_COUNT_SPIN             1212
#define IDC_BLOCK_COLOR                 1212
#define IDC_NO_MAX_LEAD                 1213
#define IDC_VAR_COLOR                   1213
#define IDC_DEFINITION_COLOR            1214
#define IDC_ROW_COUNT                   1215
#define IDC_GROUP_COLOR                 1215
#define IDC_ROW_COUNT_SPIN              1216
#define IDC_PLAIN_LEAD_TOKEN_COLOR      1216
#define IDC_FONT_NAME                   1217
#define IDC_FONT_SIZE                   1218
#define IDC_NOTES_COLOR                 1219
#define IDC_NOTES_FONT_NAME             1219
#define IDC_NOTES_FONT_SIZE             1220
#define IDC_CIRCLE_EDIT                 1221
#define IDC_CIRCLE_SPIN                 1222
#define IDC_NO_MAX_CIRCLE               1223
#define IDC_BLOCK_LETTER                1224
#define IDC_OMIT_INC                    1226
#define IDC_PARTS                       1227
#define IDC_TOWER_NUMBER                1229
#define IDC_TOWER_NAME                  1230
#define IDC_TOUCH_NAME                  1230
#define IDC_TOWER_SPEED                 1233
#define IDC_TOWER_QUALITY               1234
#define IDC_TOWER_SMALLER_FRONT         1235
#define IDC_TOWER_SMALLER_BACK          1236
#define IDC_TOWER_COVER                 1242
#define IDC_TOWER_EXTRA_COVERFOR_ODD_BELLS 1242
#define IDC_OPTIONS_TOWER_COMBO         1243
#define IDC_OPTIONS_TOWER_EDIT          1244
#define IDC_OPTIONS_TOWER_ADD           1245
#define IDC_OPTIONS_TOWER_DEL           1246
#define IDC_OPTIONS_TOWER_CLONE         1247
#define IDC_OPTIONS_TOWER_TEST          1248
#define IDC_CALL_POS_TAB                1250
#define IDC_DEFINITION                  1256
#define IDC_AGREGATE_NAME               1259
#define IDC_PROPERTY_HINT               1259
#define IDC_PROPERTY_HINT2              1260
#define IDC_USE_WORKING_DIR             1260
#define IDC_ADD_AGREGATE                1261
#define IDC_AGREGATE                    1262
#define IDC_CALL_POS_SEL                1263
#define IDC_NO_MAX_FALSENESS            1264
#define IDC_FALSENESS_EDIT              1265
#define IDC_FALSENESS_SPIN              1266
#define IDC_START_AT_ROW_COUNT_SPIN     1267
#define IDC_ROUNDS                      1268
#define IDC_DEF_CALL                    1269
#define IDC_DEF_SPLICE                  1270
#define IDC_IMPORT_LIBERARY             1272
#define IDC_LIST_LOG                    1273
#define IDC_EXPLORE_STATIS              1274
#define IDC_BELLS                       1276
#define IDC_HANDSTROKE                  1277
#define IDC_BACK                        1278
#define IDC_CC_LIB_LOAD                 1285
#define IDC_NEAR_PLACE_M                1286
#define IDC_TEMPLATE_BUTT               1287
#define IDC_DIRECTORY                   1288
#define IDC_NAME_TEMPLATE               1289
#define IDC_DIRETCORY_BUTT              1290
#define IDC_FILTER_COMBO                1291
#define IDC_FILTER_BUTT                 1292
#define IDC_ADD_METHOD                  1293
#define IDC_SPECIAL_EDIT                1293
#define IDC_EXPLORER_FIND               1293
#define IDC_FIND_METHOD                 1294
#define IDC_FLATTEN_BUTT                1294
#define IDC_EXPLORE_METHOD              1295
#define IDC_COURSE_BASED                1295
#define IDC_EDIT_COPY                   1295
#define IDC_LEAD_BASED                  1296
#define IDC_EDIT_PASTE                  1296
#define IDC_CRU_BREAKDOWN               1297
#define IDC_EDIT_CUT                    1297
#define IDC_METHOD_NAME                 1298
#define IDC_SHOW_CHANGE                 1298
#define IDC_LOCATION                    1299
#define IDC_SNAP_START                  1301
#define IDC_WORKING_DIR                 1302
#define IDC_LE                          1302
#define IDC_WORKING_DIR_BUTT            1303
#define IDC_LH                          1303
#define IDC_SHORTHAND                   1304
#define IDC_SINGLE_BLOCK                1305
#define IDC_RW_REF                      1305
#define IDC_MULTI_BLOCK                 1306
#define IDC_DATE_TOWER                  1306
#define IDC_BLOCK_COUNT                 1307
#define IDC_DATEHAND                    1307
#define IDC_BLOCK_COUNT_SPIN            1308
#define IDC_CCC                         1308
#define IDC_SPLICE_SPIN                 1309
#define IDC_PMM                         1309
#define IDC_SPLICE_EDIT                 1310
#define IDC_TDMM                        1310
#define IDC_USE_DEFAULT_SPLICES         1311
#define IDC_SPLICES                     1312
#define IDC_MUG                         1312
#define IDC_ADD_DEFAULT_SPLICES         1313
#define IDC_ADD_SPLICE                  1314
#define IDC_REMOVE_SPLICE               1315
#define IDC_ROW                         1316
#define IDC_ROW_SPIN                    1317
#define IDC_COURSE_HEAD                 1321
#define IDC_COURSE_HEAD_SPIN            1322
#define IDC_BOTTOM                      1328
#define IDC_BOTTOM_SPIN                 1329
#define IDC_PRT_TOUCH                   1330
#define IDC_PRT_FALSENESS               1330
#define IDC_PRT_STATUS                  1331
#define IDC_PRT_MUSIC                   1332
#define IDC_PRT_COURSE_HEADS            1333
#define IDC_PRT_SPLICE                  1334
#define IDC_PRT_ALL_WORK                1335
#define IDC_PRT_MULTI_BLOCK             1336
#define IDC_PRT_COURSE_HEADS2           1337
#define IDC_PRT_LEAD_ENDS               1337
#define IDC_PRT_CALLS_MADE              1338
#define ID_PRINT                        1339
#define ID_PREVIEW                      1340
#define IDC_MESSAGE                     1341
#define IDC_PRT_SPLICE_TRANSITION       1341
#define IDC_STATIC_NOT                  1343
#define IDC_OVERRIDE0                   1344
#define IDC_OVERRIDE1                   1345
#define IDC_TENOR_NOTE                  1345
#define IDC_OVERRIDE2                   1346
#define IDC_OVERRIDE3                   1347
#define IDC_TENOR_NOTE_MINUS            1348
#define IDC_NOTE                        1349
#define IDC_SAVE_STYLE_TOUCH            1350
#define IDC_LINE_STATIC                 1352
#define IDC_FIND_WHAT                   1353
#define IDC_PRINT_COLUMNS               1354
#define IDC_TOUCH_STYLE_COLOR           1355
#define IDC_HIGHER                      1356
#define IDC_LOWER                       1357
#define IDC_CRIB_LIST                   1357
#define IDC_ODD                         1358
#define IDC_EVEN                        1359
#define IDC_IN_COURSE                   1359
#define IDC_CALLED_CHANGE_LIST_DUMMY    1360
#define IDC_CALLED_CHANGE_LIST          1361
#define IDC_SPECIFY                     1362
#define IDC_CC_OPTIONS                  1363
#define IDC_CHECK1                      1364
#define IDC_CC_STATR_AGAIN              1364
#define IDC_INCLUDE_TENOR               1364
#define IDC_USE_MAPS                    1364
#define IDC_CASE                        1364
#define IDC_APPROX                      1364
#define IDC_3D_ENABLE                   1364
#define IDC_USER_IN_CENTER              1364
#define IDC_USE_STRIKING_ERRORS         1364
#define IDC_HIDE_VISUAL_FEEDBACK        1364
#define IDC_ADD_SPEECH_CALLS            1364
#define IDC_KEYBOARD_SHORTCUTS          1364
#define IDC_RADIO1                      1365
#define IDC_CC_PLAY_LIVE                1365
#define IDC_CALL_TYPE                   1365
#define IDC_MILES                       1365
#define IDC_CONNECTION_STYLE            1365
#define IDC_STYLE                       1365
#define IDC_ASCENDING                   1365
#define IDC_WEIGHT_LOGIC                1365
#define IDC_TOUCH_WINDOW                1365
#define IDC_UPLET                       1365
#define IDC_BACKLEFT                    1365
#define IDC_HOME_USE                    1365
#define IDC_START_AT_ROW0               1365
#define IDC_RADIO2                      1366
#define IDC_CC_STOP                     1366
#define IDC_CHECK2                      1367
#define IDC_CC_PREVIEW                  1367
#define IDC_AFFECT2                     1367
#define IDC_LOCATION_TYPE2              1367
#define IDC_CLOCKWISE                   1367
#define IDC_QUIET                       1367
#define IDC_FOLLOW_PREVIOUS_BELL        1367
#define IDC_USING_SIMULATOR             1367
#define IDC_MICROPHONE_NAMES            1367
#define IDC_RADIO5                      1367
#define IDC_CHECK3                      1368
#define IDC_CC_UNDO                     1368
#define IDC_AFFECT3                     1368
#define IDC_PREV_ERROR                  1368
#define IDC_LOCKHANDBACK                1368
#define IDC_COM2                        1368
#define IDC_RADIO6                      1368
#define IDC_CHECK4                      1369
#define IDC_CC_REWIND                   1369
#define IDC_LOCK_HAND_BACK              1369
#define IDC_COM3                        1369
#define IDC_SEP1                        1370
#define IDC_RADIO7                      1370
#define IDC_COM4                        1370
#define IDC_SEP2                        1371
#define IDC_CC_COPY                     1372
#define IDC_EDIT1                       1373
#define IDC_CC_SEEK                     1373
#define IDC_PULL_PER_CHANGE             1373
#define IDC_PORT                        1373
#define IDC_TEXT                        1373
#define IDC_SIZE_EDIT                   1373
#define IDC_REPEAT_EDIT_START           1373
#define IDC_VAL1                        1373
#define IDC_FREQ                        1373
#define IDC_SEP3                        1374
#define IDC_PULL_PER_CHANGE_SPIN        1374
#define IDC_DISTANCE_SPIN               1374
#define IDC_VAL2                        1374
#define IDC_REPEAT_EDIT_END             1374
#define IDC_PATH1                       1374
#define IDC_VOL                         1374
#define IDC_CC_STYLE                    1375
#define IDC_PEAL_SPEED                  1375
#define IDC_VAL3                        1375
#define IDC_HAND_LEAD                   1375
#define IDC_CWT                         1376
#define IDC_VAL4                        1376
#define IDC_KG                          1377
#define IDC_VAL5                        1377
#define IDC_KM                          1378
#define IDC_VAL6                        1378
#define IDC_SPIN1                       1379
#define IDC_IPADDRESS1                  1379
#define IDC_IP_ADDRESS                  1379
#define IDC_OPTIONS_USERS_EDIT          1380
#define IDC_SPIN2                       1380
#define IDC_SPIN3                       1381
#define IDC_OPTIONS_USERS_ADD           1381
#define IDC_SPIN4                       1382
#define IDC_OPTIONS_USERS_DEL           1382
#define IDC_SPIN5                       1383
#define IDC_OPTIONS_USER_COMBO          1383
#define IDC_SPIN6                       1384
#define IDC_SPIN7                       1384
#define IDC_CONDITION                   1385
#define IDC_BOTTOM_LINE                 1386
#define IDC_NOTE4                       1387
#define IDC_TOWER_COMBO                 1388
#define IDC_GRID_LOC                    1389
#define IDC_DISTANCE_LOGIC              1390
#define IDC_DISTANCE_LOGIC1             1391
#define IDC_DISTANCE                    1392
#define IDC_LOCATION_TYPE               1393
#define IDC_LOCATION_TYPE1              1394
#define IDC_DISTANCE_LABEL              1395
#define ID_MAKE_CIRCLE                  1396
#define IDC_RIGHT                       1397
#define IDC_ALL_RIGHT                   1398
#define IDC_LIST_RIGHT                  1399
#define IDC_ALL_LEFT                    1400
#define IDC_TOWER                       1400
#define IDC_DATE                        1401
#define IDC_UP                          1401
#define IDC_BELL_GO                     1402
#define IDC_DOWN                        1402
#define IDC_BELL_SOUND                  1403
#define IDC_RESET                       1403
#define IDC_REMOVE                      1403
#define IDC_COMMENTS                    1404
#define IDC_USE_PROXY                   1408
#define IDC_STATIC_IP                   1409
#define IDC_STATIC_PORT                 1410
#define IDC_TEST_CONNECTION             1411
#define IDC_RADIO3                      1412
#define IDC_RADIO4                      1413
#define IDC_DESCINDING                  1415
#define IDC_AND                         1416
#define IDC_OR                          1417
#define IDC_WEIGHT_LOGIC1               1418
#define IDC_WEIGHT_LOGIC2               1419
#define IDC_TOWER_DUMMY                 1420
#define IDC_DATETIMEPICKER1             1424
#define IDC_DATETIMEPICKER2             1425
#define IDC_QR                          1433
#define IDC_LB                          1434
#define IDC_STATIC_KG                   1435
#define IDC_STATIC_CWT                  1436
#define IDC_STATIC_QR                   1437
#define IDC_STATIC_LB                   1438
#define IDC_WEIGHT1                     1439
#define IDC_WEIGHT2                     1440
#define IDC_SPIN_LB                     1440
#define IDC_SPIN_CWT                    1442
#define IDC_SPIN_QR                     1443
#define IDC_STATIC_NAME                 1444
#define IDC_UPDATE_CHECK                1445
#define IDC_PROVIDERS                   1446
#define IDC_LINK                        1447
#define IDC_SIZE_SPIN                   1448
#define IDC_CLEAR_CACHE                 1449
#define IDC_STATIC_MB                   1450
#define IDC_STATIC_CACHE                1451
#define IDC_STATIC_PROVIDER             1452
#define IDC_STATIC_SP_VERSION           1453
#define IDC_STATIC_SP_VERSION_TEXT      1454
#define IDC_LAUNCH_STYLE                1455
#define IDC_EXTERNAL_LAUNCH             1456
#define IDC_CRIB_FONT_NAME              1457
#define IDC_CRIB_FONT_SIZE              1458
#define IDC_CRIB_FONT_COLOR             1459
#define IDC_REPEAT_SPIN                 1460
#define IDC_REPEAT_SPIN_START           1460
#define IDC_DOCUMENT_TYPE               1461
#define IDC_REPEAT_SPIN_END             1461
#define IDC_CRIB_DOC                    1462
#define IDC_BLUE_LINE_WINDOW            1463
#define IDC_SYSTEM_SETUP                1464
#define IDC_BUTTON1                     1465
#define IDC_DETAILS0                    1465
#define IDC_VOLUME_RESET                1465
#define IDC_STOP                        1465
#define IDC_RESET_VOL                   1465
#define IDC_NEXT_MBI                    1465
#define IDC_RECONNECT                   1465
#define IDC_APPLY_ALL                   1465
#define IDC_RESET_TOWERS                1465
#define IDC_COMBO1                      1466
#define IDC_COM_PORT                    1466
#define IDC_TEST0                       1466
#define ID_ZOOM_IN                      1466
#define IDC_OVERALL_FREQUENCY_RESET     1466
#define IDC_RESET_FREQ                  1466
#define IDC_SIGNAL                      1466
#define IDC_PREVIEW                     1466
#define IDC_BELL                        1466
#define IDC_TRAINING                    1467
#define IDC_DETAILS1                    1467
#define ID_ZOOM_OUT                     1467
#define IDC_SETUP                       1468
#define IDC_TEST1                       1468
#define ID_CENTER                       1468
#define IDC_TRAINING2                   1469
#define IDC_DETAILS2                    1469
#define ID_CENTER_OF_GRAVITY            1469
#define IDC_BUTTON3                     1470
#define IDC_SETTINGS                    1470
#define IDC_TEST2                       1470
#define ID_APPLY                        1470
#define IDC_BUTTON4                     1471
#define IDC_NEW_PROFILE                 1471
#define IDC_DETAILS3                    1471
#define ID_CENTER2                      1471
#define IDC_REMOVE_ALL                  1472
#define IDC_SPEECHVOICES                1473
#define IDC_REMOVE_ALL2                 1473
#define IDC_DETAILS4                    1473
#define IDC_ENABLE                      1474
#define IDC_EDIT0                       1474
#define IDC_LABEL                       1475
#define IDC_VOLUME                      1476
#define IDC_EDIT2                       1476
#define IDC_SYSTEM_VOLUME               1477
#define IDC_EDIT3                       1477
#define IDC_PATH0                       1478
#define IDC_STATIC_QUITET               1479
#define IDC_PATH2                       1479
#define IDC_STATIC_LOUD                 1480
#define IDC_PATH3                       1480
#define IDC_SPEED                       1481
#define IDC_EDIT4                       1481
#define IDC_STATIC_VOLUME               1482
#define IDC_PATH4                       1482
#define IDC_STATIC_SETUP                1483
#define IDC_EDIT5                       1483
#define IDC_STATIC_FAST                 1484
#define IDC_PATH5                       1484
#define IDC_STATIC_SLOW                 1485
#define IDC_DETAILS6                    1485
#define IDC_STATIC_SPEED                1486
#define IDC_EDIT6                       1486
#define IDC_STATIC_VOICES               1487
#define IDC_PATH6                       1487
#define IDC_VOICES                      1488
#define IDC_DETAILS7                    1488
#define IDC_CONFIG_MIC                  1489
#define IDC_EDIT7                       1489
#define IDC_DELETE_PROFILE              1490
#define IDC_PATH7                       1490
#define IDC_LANGUAGE                    1491
#define IDC_MIC_LEVEL                   1492
#define IDC_PROFILE_COMBO               1493
#define IDC_TRAIN                       1494
#define IDC_STATIC_PROFILE              1495
#define IDC_STATIC_LANGUAGE             1496
#define IDC_STATIC_MICROPHONE           1497
#define IDC_STATIC_TEST_WORDS           1498
#define IDC_STATIC_MICROPHONE2          1498
#define IDC_DETECTED_WORDS              1499
#define IDC_STATIC_MICROPHONE3          1499
#define IDC_CONNECT_MSG                 1500
#define IDC_STATIC_PORTS                1500
#define IDC_CONNECT_ICON                1501
#define IDC_STATIC_MICROPHONE5          1501
#define IDC_STATIC_DEBOUNCE             1501
#define IDC_NAME1                       1502
#define IDC_STATIC_DEBOUNCE2            1502
#define IDC_NAME2                       1503
#define IDC_STATIC_PORTS2               1503
#define IDC_NAME3                       1504
#define IDC_NAME4                       1505
#define IDC_NAME5                       1506
#define IDC_NAME6                       1507
#define IDC_PIC1                        1508
#define IDC_PIC2                        1509
#define IDC_PIC3                        1510
#define IDC_PIC4                        1511
#define IDC_PIC5                        1512
#define IDC_PIC6                        1513
#define IDC_STATUS_STATIC               1514
#define IDC_DELAYS_STATIC               1515
#define IDC_FREQ_SPIN                   1516
#define IDC_STATIC_NOTE2                1517
#define IDC_STATIC_NOTE1                1518
#define IDC_STATIC_POLL_INTERVAL        1519
#define IDC_STATIC_DELAY                1520
#define IDC_STATIC_TRIG                 1521
#define IDC_STATIC_TOWER                1522
#define IDC_SCROLLBAR1                  1523
#define IDC_STATIC_STROKE0              1526
#define IDC_STATIC_BELL0                1527
#define IDC_STATIC_BELL1                1528
#define IDC_STATIC_STROKE1              1529
#define IDC_BUTTON2                     1530
#define IDC_EDIT_POS                    1530
#define IDC_AUTHOR_FONT                 1530
#define IDC_BELL_NO_FONT                1530
#define IDC_RESET_ALL                   1530
#define ID_CREATE_BLANK                 1530
#define IDC_MAIN_FONT                   1531
#define IDC_STATIC_BELL2                1532
#define IDC_NOTES_FONT                  1532
#define IDC_STATIC_STROKE2              1533
#define IDC_TEST5                       1534
#define IDC_TEST6                       1535
#define IDC_STATIC_BELL3                1536
#define IDC_STATIC_STROKE3              1537
#define IDC_STATIC_BELL4                1538
#define IDC_STATIC_COVER                1539
#define IDC_STATIC_STROKE4              1539
#define IDC_STATIC_COVER2               1540
#define IDC_STATIC_BELL5                1540
#define IDC_3D_DUMMY                    1541
#define IDC_STATIC_STROKE5              1541
#define IDC_STATUS                      1542
#define IDC_STATIC_BELL6                1542
#define IDC_NUMBER_SPIN                 1543
#define IDC_STATIC_STROKE6              1543
#define IDC_CREATE_TOWER_STATIC_LINE    1544
#define IDC_TEST7                       1544
#define IDC_CREATE_TOWER_STATIC         1545
#define IDC_STATIC_BELL7                1545
#define IDC_CREATE_TOWER_STATIC2        1546
#define IDC_STATIC_STROKE7              1546
#define IDC_CREATE_TOWER_STATIC_LINE2   1547
#define IDC_CREATE_TOWER_STATIC_LINE6   1547
#define IDC_TEST8                       1547
#define IDC_FREQUENCY                   1548
#define IDC_PITCH                       1548
#define IDC_CREATE_TOWER_STATIC3        1548
#define IDC_CREATE_TOWER_STATIC_LINE7   1548
#define IDC_VOLUME_SPIN                 1549
#define IDC_CREATE_TOWER_STATIC_LINE3   1549
#define IDC_PITCH_SPIN                  1550
#define IDC_CREATE_TOWER_STATIC4        1550
#define IDC_TEST                        1551
#define IDC_OPTIONS_PROFILE_COMBO       1552
#define IDC_OPTIONS_PROFILE_CLONE       1553
#define IDC_OPTIONS_PROFILE_EDIT        1554
#define IDC_OPTIONS_PROFILE_ADD         1555
#define IDC_OPTIONS_PROFILE_DEL         1556
#define IDC_STATIC1                     1557
#define IDC_INPUTS_SCROLL               1558
#define IDC_VERSION                     1559
#define IDC_LINES_SCROLL                1560
#define IDC_TREE                        1561
#define IDC_ROW_EDIT                    1562
#define IDC_RESIZEEW                    1563
#define AAA_PROP_ROOT_BUTTON_METHOD     1564
#define IDC_ROW_MSG                     1565
#define IDC_FPOINT                      1566
#define IDC_LEAD_END                    1567
#define IDC_OPTIONS_LINES_STYLE_COMBO   1568
#define IDC_NUMBER                      1569
#define IDC_DLG_FRAME                   1570
#define IDC_METERS                      1571
#define IDC_OPTIONS_LINES_ADD           1572
#define IDC_SPLICE                      1573
#define IDC_OPTIONS_LINES_DEL           1574
#define IDC_VISUAL_EDIT                 1575
#define IDC_OPTIONS_LINES_EDIT          1576
#define IDC_SEARCH_NOTATION             1577
#define IDC_CAPTION_BAR                 1578
#define IDC_NOTATION_STATIC             1579
#define IDC_REMOVE_CALL                 1580
#define IDC_PAGE_TREE                   1581
#define IDC_GENERIC_EDIT                1582
#define IDC_LEAD_END_STATCI             1583
#define IDC_LEAD_END_TITLE_STATIC       1584
#define IDC_ASYM                        1585
#define IDC_STATIC_TEXT                 1586
#define IDC_METHOD_EXPLORER             1587
#define IDC_SEARCH_NAME                 1588
#define IDC_DELETE_METHOD               1589
#define IDC_CHANNEL                     1590
#define IDC_CHANNEL_SPIN                1591
#define IDC_PORTS                       1592
#define IDC_DEBOUNCE                    1593
#define IDC_DEBOUNCE_SPIN               1594
#define IDC_STATIC_MS                   1595
#define IDC_STATIC_NOTE                 1596
#define IDC_POLL_INTERVAL               1596
#define IDC_POLL_INTERVAL_SPIN          1597
#define IDC_STATIC_MS2                  1598
#define IDC_COMBO2                      1598
#define IDC_COMBO3                      1599
#define IDC_TYPE                        1599
#define IDC_COMBO4                      1600
#define IDC_COUNT                       1600
#define IDC_NEXT_PORT_CONTROL           1601
#define IDC_DELAY_SPIN                  1602
#define IDC_DELAY                       1603
#define IDC_KEY_STATIC                  1604
#define IDC_WORD                        1605
#define IDC_FILE_NAME                   1606
#define IDC_FIRST_SIMULATED_BELL        1607
#define IDC_FIRST_SIMULATED_BELL_SPIN   1608
#define IDC_HANDLEFT                    1611
#define IDC_BACKRIGHT                   1612
#define IDC_HANDRIGHT                   1613
#define IDC_HAND_LATENESS               1614
#define IDC_BACK_LATENESS               1615
#define IDC_VAL_SPIN                    1615
#define IDC_HAND_QUALITY                1616
#define IDC_VAL                         1616
#define IDC_BACK_QUALITY                1617
#define IDC_COVER_COUNT_EDIT            1617
#define IDC_COVER_COUNT_SPIN            1618
#define IDC_DETAILS5                    1619
#define IDC_TEST4                       1620
#define IDC_TEST3                       1621
#define IDC_STATIC_RESOLITION           1622
#define IDC_BELLS_AFFECTED              1623
#define IDC_BELLS_AFFECTED_SPIN         1624
#define IDC_MAX_ERROR                   1625
#define IDC_STATIC_PATH                 1626
#define IDC_TOWER_USE_SERIAL            1627
#define IDC_TOWER_USE_MBI               1628
#define IDC_ONE_REFLECTOR               1629
#define IDC_TWO_REFLECTOR               1630
#define IDC_COM1                        1631
#define IDC_IDC_START_AT_ROW1           1632
#define IDC_MATRIX_FILTER_NAME          1633
#define IDC_CALLED_CAHNGE_BASE          2000
#define ID_TOOLS_OPTIONS                32771
#define ID_TOOLS_STYLE                  32777
#define ID_WINDOW_MANAGER               32784
#define ID_POPUP_ADDWORK_SINGLEDODGE    32785
#define ID_POPUP_ADDWORK_DOUBLE_DODGE   32798
#define ID_POPUP_ADDWORK_PLACESUP       32799
#define ID_POPUP_ADDWORK_PLACESDOWN     32800
#define ID_POPUP_ADDWORK_YORKSHIREUP    32803
#define ID_POPUP_ADDWORK_YORKSHIREDOWN  32804
#define ID_POPUP_ADDWORK_CAMBRIDGEUP    32805
#define ID_POPUP_ADDWORK_CAMBRIDGEDOWN  32806
#define ID_POPUP_DELETE                 32808
#define ID_TOUCH_ADDVARIANCE            32822
#define ID_TOUCH_PROVE                  32827
#define ID_ADD_NOTATION                 32836
#define ID_POPUP_STYLE                  32840
#define ID_HELP_TIPOFTHEDAY             32886
#define ID_VIEW_MUSIC                   32889
#define ID_VIEW_PROPERTIES              32891
#define ID_VIEW_TOUCH_MAIN_TOOLBAR      32897
#define ID_VIEW_TOUCH_BLUE_LINE_TOOLBAR 32898
#define ID_VIEW_STANDARD_TOOLBAR        32899
#define ID_METHOD_STYLE_DUMMY           32900
#define ID_VIEW_WORKSPACE               32903
#define ID_VIEW_OUTPUT                  32904
#define ID_LINECOLOR                    32906
#define ID_LINEWIDTH_1                  32909
#define ID_LINEWIDTH_2                  32910
#define ID_LINEWIDTH_3                  32911
#define ID_TOOLS_ENTRY                  32915
#define ID_USER_TOOL1                   32916
#define ID_USER_TOOL2                   32917
#define ID_USER_TOOL3                   32918
#define ID_USER_TOOL4                   32919
#define ID_USER_TOOL5                   32920
#define ID_USER_TOOL6                   32921
#define ID_USER_TOOL7                   32922
#define ID_USER_TOOL8                   32923
#define ID_USER_TOOL9                   32924
#define ID_USER_TOOL10                  32925
#define ID_WINDOW_CLOSE                 32939
#define ID_FILE_SAVEALL                 32941
#define ID_HELP_KEYBOARDMAP             32943
#define ID_INSERT_ROW                   32945
#define ID_INSERT_COLUMN                32946
#define ID_TOUCH_DELETROW               32947
#define ID_DELETE_COLUMN                32949
#define ID_SHOW_GRID                    32954
#define ID_DELETE_ROW                   32955
#define ID_POPUP_ADDBLOCKDEFINITION     32958
#define ID_ADDBLOCKDEFINITION           32960
#define ID_DELETEBLOCK                  32961
#define ID_ADDBLOCKDEFINITION_MENU      32962
#define ID_EDITBLOCKLETTER              32965
#define ID_EDIT_VARIANCE                32967
#define ID_HELP_FIND                    32968
#define ID_VIEW_PLAY_TOOLBAR            32969
#define ID_VIEW_CUSTOMIZE               32970
#define ID_PAUSE                        32971
#define ID_STOP                         32972
#define ID_TOWER                        32973
#define ID_VIEW_RECORD_TOOLBAR          32974
#define ID_VIEW_RECORD_LOGIC_TOOLBAR    32975
#define ID_VIEW_USER_TOOLBAR1           32993
#define ID_VIEW_USER_TOOLBAR2           32994
#define ID_VIEW_USER_TOOLBAR3           32995
#define ID_VIEW_USER_TOOLBAR4           32996
#define ID_VIEW_USER_TOOLBAR5           32997
#define ID_VIEW_USER_TOOLBAR6           32998
#define ID_VIEW_USER_TOOLBAR7           32999
#define ID_VIEW_USER_TOOLBAR8           33000
#define ID_VIEW_USER_TOOLBAR9           33001
#define ID_VIEW_USER_TOOLBAR10          33002
#define ID_EDIT_DELETE                  33003
#define ID_EDIT_DELETE_BACK             33004
#define ID_EDIT_DELETE_WORD_BACK        33005
#define ID_EDIT_TAB                     33006
#define ID_EDIT_UNTAB                   33007
#define ID_EDIT_SWITCH_OVRMODE          33008
#define ID_EDIT_CHAR_LEFT               33010
#define ID_EDIT_EXT_CHAR_LEFT           33011
#define ID_EDIT_CHAR_RIGHT              33012
#define ID_EDIT_EXT_CHAR_RIGHT          33013
#define ID_EDIT_WORD_LEFT               33014
#define ID_EDIT_EXT_WORD_LEFT           33015
#define ID_EDIT_WORD_RIGHT              33016
#define ID_EDIT_EXT_WORD_RIGHT          33017
#define ID_EDIT_LINE_UP                 33018
#define ID_EDIT_EXT_LINE_UP             33019
#define ID_EDIT_LINE_DOWN               33020
#define ID_EDIT_EXT_LINE_DOWN           33021
#define ID_EDIT_SCROLL_UP               33022
#define ID_EDIT_SCROLL_DOWN             33023
#define ID_EDIT_PAGE_UP                 33024
#define ID_EDIT_EXT_PAGE_UP             33025
#define ID_EDIT_PAGE_DOWN               33026
#define ID_EDIT_EXT_PAGE_DOWN           33027
#define ID_EDIT_LINE_END                33028
#define ID_EDIT_EXT_LINE_END            33029
#define ID_EDIT_LINE_HOME               33030
#define ID_EDIT_EXT_TEXT_HOME           33031
#define ID_EDIT_TEXT_HOME               33032
#define ID_EDIT_EXT_LINE_HOME           33033
#define ID_EDIT_TEXT_END                33034
#define ID_EDIT_EXT_TEXT_END            33035
#define ID_EDIT_FIND_PREVIOUS           33036
#define ID_EDIT_DELETE_WORD             33037
#define AFX_IDS_HELPMODEMESSAGE2        33038
#define ID_SHOW_COURSE_HEADS            33043
#define ID_TOUCH_ADDDEFINITION          33046
#define ID_INC_LEAD                     33049
#define ID_DEC_LEAD                     33050
#define ID_SET_START_AT_ROW             33052
#define ID_SET_END_AT_ROW               33053
#define ID_EDIT_GROUP                   33054
#define ID_ME_NEW_FOLDER                33056
#define ID_ME_NEW_METHOD                33057
#define ID_POPUP_EDIT                   33064
#define ID_ME_LIST_EDIT                 33065
#define ID_ME_LIST_DELETE               33067
#define ID_POPUP_DELETEFOLDER           33070
#define ID_ME_DELETE_FOLDER             33071
#define ID_ME_RENAME_METHOD             33072
#define ID_ME_RENAME_FOLDER             33073
#define ID_ME_PREVIEW                   33074
#define ID_ME_INFO                      33076
#define ID_TOUCH_ADDMUSIC               33078
#define ID_ME_LIST_VIEW                 33080
#define ID_EDIT_GOTO                    33081
#define ID_SPEED_UP                     33082
#define ID_SLOW_DOWN                    33083
#define ID_EDIT_TOWER_DETAILS           33084
#define ID_PRINT_ANALYSIS               33088
#define ID_FILE_PRINT_TOOLBAR           33090
#define ID_FILE_PRINT_MENU              33092
#define ID_POPUP_PRINT_ANALYSIS         33095
#define ID_TOOLS_CONVERTOCOURSEBASE     33096
#define ID_TOOLS_CONVERTOLEADBASE       33097
#define ID_TOOLS_DATABASEMAINTAINANCE   33099
#define ID_SHOW_LEADHEAD                33100
#define ID_ME_CRIBMETHOD                33101
#define ID_TOOLS_CALLCHANGEEDITOR       33102
#define ID_TOWER_SOUND_OPTIONS          33103
#define ID_POPUP_OPTIONS                33104
#define ID_TOUCH_OPTIONS                33105
#define ID_TOWER_OPTIONS                33106
#define ID_METHOD_OPTIONS               33107
#define ID_POPUP_EDITNOTES              33108
#define ID_TOWER_SORT                   33109
#define ID_TOWER_DATABASE               33110
#define ID_MAP_TEST                     33112
#define ID_POPUP_SHOWMAP                33113
#define ID_SET_HOME_TOWER               33114
#define ID_USER_OPTIONS                 33116
#define ID_GRAB_OPTIONS                 33117
#define ID_TOWER_SETHOMETOWER           33118
#define ID_POPUP_GRABTOWER              33119
#define ID_POPUP_SETHOMETOWER           33120
#define ID_GRABS                        33121
#define ID_POPUP_EDITGRAB               33122
#define ID_GRABS_ADDTOWERGRAB           33129
#define ID_POPUP_EDITDAYORDER           33131
#define ID_POPUP_NEWGRAB                33132
#define ID_POPUP_DELETEGRAB             33133
#define ID_ADDTOWER                     33134
#define ID_DELETETOWER                  33135
#define ID_PLAY                         33136
#define ID_SHOW_ALL                     33138
#define ID_POPUP_EDITTOWER              33139
#define ID_EDITTOWER                    33140
#define ID_FILTER_APPLY                 33181
#define ID_FILTER                       33182
#define ID_INVERT_SELECTION             33186
#define ID_MEMORY_ASSIGN                33187
#define ID_MEMORY_SWAP                  33188
#define ID_MEMORY_OR                    33190
#define ID_MEMORY_AND                   33191
#define ID_MEMORY_MINUS                 33192
#define IDTEMPHOLD                      33194
#define ID_USERFILTERMORE               33199
#define ID_USERFILTERDUMMY              33200
#define ID_STOCKFILTERDUMMY             33250
#define ID_POPUP_DELETETOWER            33300
#define ID_DELETEGRAB                   33301
#define ID_MEMORY_REMOVE_ITEM           33302
#define ID_MEMORY_ADD_ITEM              33303
#define ID_POPUP_EDIT_COPY              33304
#define ID_LAUNCH_WEB_PAGE              33305
#define ID_MAP_OPTIONS                  33309
#define ID_VIEW_INTERNET_TOOLBAR        33317
#define ID_VIEW_ADDRESS_BAR             33318
#define ID_VIEW_STOP                    33320
#define ID_VIEW_REFRESH                 33321
#define ID_LINK_1                       33322
#define ID_VIEW_FONTS_LARGEST           33323
#define ID_VIEW_FONTS_LARGE             33324
#define ID_VIEW_FONTS_MEDIUM            33325
#define ID_VIEW_FONTS_SMALL             33326
#define ID_VIEW_FONTS_SMALLEST          33327
#define ID_GO_BACK                      33328
#define ID_GO_FORWARD                   33329
#define ID_GO_START_PAGE                33330
#define ID_GO_SEARCH_THE_WEB            33331
#define ID_GO_BEST_OF_THE_WEB           33332
#define ID_FAVORITES_DROPDOWN           33333
#define ID_FONT_DROPDOWN                33334
#define ID_HELP_WEB_TUTORIAL            33335
#define ID_HELP_ONLINE_SUPPORT          33336
#define ID_HELP_MICROSOFT_ON_THE_WEB_FREE_STUFF 33337
#define ID_HELP_MICROSOFT_ON_THE_WEB_GET_FASTER_INTERNET_ACCESS 33338
#define ID_HELP_MICROSOFT_ON_THE_WEB_FREQUENTLY_ASKED_QUESTIONS 33339
#define ID_HELP_MICROSOFT_ON_THE_WEB_SEND_FEEDBACK 33340
#define ID_HELP_MICROSOFT_ON_THE_WEB_BEST_OF_THE_WEB 33341
#define ID_HELP_MICROSOFT_ON_THE_WEB_SEARCH_THE_WEB 33342
#define ID_HELP_MICROSOFT_ON_THE_WEB_MICROSOFT_HOME_PAGE 33343
#define ID_HELP_MICROSOFT_ON_THE_WEB_INTERNET_START_PAGE 33344
#define ID_FAVORITS_DUMMY               33345
#define ID_HISTORY_DUMMY                33346
#define ID_VIEW_LINKS_BAR               33347
#define ID_VIEW_TEXTLABELS              33348
#define ID_VIEW_BACKGROUND              33349
#define ID_VIEW_EXPLORERBAR             33350
#define ID_SHOW_PUSHPINS                33351
#define ID_VIEW_MAP_TOOLBAR             33352
#define ID_SHOW_MAP                     33356
#define ID_MAP_EAST                     33359
#define ID_MAP_WEST                     33360
#define ID_MAP_SOUTH                    33361
#define ID_MAP_NORTH                    33362
#define ID_RELOAD_MAP                   33363
#define ID_CRIB_OPTIONS                 33364
#define ID_POPUP_EDITMETHOD             33366
#define ID_VIEW_CRIB_TOOLBAR            33367
#define ID_IMAGE_TEMP                   33369
#define ID_VIEW_IMAGE_TOOLBAR           33370
#define ID_BUTTON33371                  33371
#define ID_TOOLS_TRANSPOSE              33372
#define ID_TOOLS_TIDY                   33373
#define ID_TOOLS_SETDEFAULTCALLINGPOSITIONS 33374
#define ID_TOOLS_RESETTOYCH             33375
#define ID_VIEW_FULLSCREEN              33379
#define ID_SORT_HIRCH                   33380
#define ID_SORT_ALPHA                   33381
#define ID_TOUCH_MAIN_CRIB              33382
#define ID_TOUCH_MAIN_NEW_FIND          33384
#define ID_TOUCH_MAIN_NEW_EXPLORER      33385
#define ID_TOUCH_MAIN_DELETE            33387
#define ID_NEWCRIB                      33391
#define ID_NEWTOUCH                     33392
#define ID_ADD_EXPLORER_NOTATION        33394
#define ID_ADD_FIND_NOTATION            33395
#define ID_TOUCH_MAIN_ADD               33401
#define ID_TOUCH_ADDMETHOD              33402
#define ID_TOUCH_ADDMETHOD33403         33403
#define ID_MATRIX_ADDUSERFILTER         33406
#define ID_DELETE_USER_FILTER           33407
#define ID_RECORD_ADD                   33408
#define ID_MATRIX_DELETEUSERFILTER      33409
#define ID_MATRIX_APPLYUSERFILTER       33410
#define ID_VIEW_HOME_TOWER              33412
#define ID_VIEW_SELECTED_TOWER          33413
#define ID_DUMMY_ANALYSIS               33414
#define ID_Menu                         33426
#define ID_VIEW_ANALYSIS_STATUS         33428
#define ID_VIEW_ANALYSIS_FALSENESS      33429
#define ID_VIEW_ANALYSIS_MUSIC          33430
#define ID_VIEW_ANALYSIS_COURSEHEAD     33431
#define ID_VIEW_ANALYSIS_LEADEND        33432
#define ID_VIEW_ANALYSIS_ALLTHEWORK     33433
#define ID_VIEW_ANALYSIS_CALLSMADE      33434
#define ID_VIEW_ANALYSIS_MULTIBLOCK     33435
#define ID_VIEW_ANALYSIS_SPLICETRANSITION 33437
#define ID_VIEW_ANALYSIS_DUMMY          33438
#define ID_VIEW_ANALYSIS_SPLICE         33444
#define ID_MDI_NEW_HORZ_TAB_GROUP       33445
#define ID_MDI_NEW_VERT_TAB_GROUP       33446
#define ID_MDI_MOVE_TO_NEXT_GROUP       33447
#define ID_MDI_MOVE_TO_PREV_GROUP       33448
#define ID_TAB_DOCUMENT                 33457
#define ID_VIEW_TOUCH_SIMULATOR_TOOLBAR 33460
#define ID_VIEW_SIMULATOR_METHOD        33462
#define ID_VIEW_SIMULATOR_STRIKING      33467
#define ID_OVERALL_FREQ_DOWN            33471
#define ID_OVERALL_FREQ_UP              33472
#define ID_BUTTON33473                  33473
#define ID_VIEW_SIMULATOR_INPUT_SPY     33479
#define ID_SIMULATOR_OPTIONS            33482
#define ID_SIMULATOR_RESET              33483
#define ID_VIEW_PLAY_SIMULATOR_TOOLBAR  33484
#define ID_STRIKING                     33487
#define ID_BUTTON33488                  33488
#define ID_CREATE_STRIKE_REPORT         33488
#define ID_VIEW_STRIKING_CONTROLS       33490
#define ID_BUTTON33493                  33493
#define ID_PLAY_METHOD                  33494
#define ID_PLAY_ROUNDS                  33495
#define ID_STAND_UP                     33496
#define ID_Menu33497                    33497
#define ID_SIMULATOR_STRIKING_SINGLE_SET_BELL 33500
#define ID_VIEW_SIMULATOR_STRIKING_SINGLE_BELL1 33501
#define ID_VIEW_SIMULATOR_STRIKING_SINGLE_BELL2 33502
#define ID_SIMULATOR_STRIKING_SINGLE_SET_BELL2 33503
#define ID_SIMULATOR_STRIKING_SINGLE_SET_BELL1 33504
#define ID_IMAGE_ZOOMIN                 33505
#define ID_IMAGE_ZOOMOUT                33506
#define ID_PLAY_ROUNDS_AUTO             33508
#define ID_COME_ROUND_NEXT_TIME         33510
#define ID_PLAY_S                       33511
#define ID_STRIKING_TEST                33513
#define IDC_SIMULATOR_OPTIONS           33516
#define ID_PLAY_MUTE                    33517
#define ID_VIEW_TASKPANE                33518
#define ID_SHOW_BELL                    33523
#define ID_BUTTON33524                  33524
#define ID_SHOW_PLACE                   33524
#define ID_VIEW_STRIKE_TOOLBAR          33525
#define ID_VIEW_STRIKE_GRAPH            33527
#define IDT_ICONS                       33530
#define ID_TASK_LIST                    33531
#define ID_DUMMY_STRIKE_SET_BELL        33532
#define ID_BUTTON33534                  33534
#define ID_VIEW_STRIKE_INFO             33536
#define ID_BACK                         33538
#define ID_HAND                         33539
#define ID_HAND_BACK                    33540
#define ID_STRIKING_TEST_RESULTS        33541
#define ID_DUMMY_SIMULATOR_SET_BELL     33542
#define IDT_CALLS                       33543
#define ID_CALLX                        33547
#define ID_CALLY                        33548
#define ID_SINGLE                       33550
#define ID_CALLSINGLE                   33550
#define ID_BOB                          33551
#define ID_CALLBOB                      33551
#define ID_CALLS_USE_TOUCH              33552
#define ID_CALLS_PLAIN                  33553
#define ID_CALLS_RANDOM                 33554
#define ID_VIEW_TOUCH_SIMULATOR_CALLS   33557
#define ID_TOUCH_G                      33560
#define ID_CALLPLAIN                    33563
#define ID_CALLZ                        33564
#define ID_TOUCH_CALLS                  33565
#define ID_WINDOW_RESETLAYOUT           33572
#define ID_VIEW_SIMULATOR_INPUTS_MAP    33574
#define ID_BUTTON33575                  33575
#define IDC_IMPORT_BAGLEY               33576
#define ID_BUTTON33578                  33578
#define ID_MAIN_ASSIGN                  33578
#define hhh                             33579
#define ID_WINDOW_CLOSEALL              0xE13F

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        551
#define _APS_NEXT_COMMAND_VALUE         33580
#define _APS_NEXT_CONTROL_VALUE         1634
#define _APS_NEXT_SYMED_VALUE           488
#endif
#endif
